apiVersion: v1
kind: Service
metadata:
  name: {{ include "Hellocockatiel.fullname" . }}
  labels:
    {{- include "Hellocockatiel.labels" . | nindent 4 }}
spec:
  type: {{ .Values.service.type }}
  ports:
    - port: {{ .Values.service.port }}
      targetPort: http
      protocol: TCP
      name: devport
  selector:
    {{- include "Hellocockatiel.selectorLabels" . | nindent 4 }}